# Generated by Django 4.2 on 2023-11-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_roll_no_alter_student_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
